name: weather_today
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0    

  cupertino_icons: ^1.0.2
  flutter_glow: ^0.3.0
  provider: ^6.0.5
  logger: ^1.1.0
  flutter_screenutil: ^5.7.0
  flutter_dotenv: ^5.0.2
  dio: ^4.0.4
  http: ^0.13.4
  firebase_core: ^2.8.0
  firebase_dynamic_links: ^5.0.17
  firebase_core_platform_interface: ^4.5.3
  shimmer: ^2.0.0
  kakao_map_plugin: ^0.1.2
  kakao_flutter_sdk: ^1.3.1
  shared_preferences: ^2.1.0
  vibration: ^1.7.6
  permission_handler: ^10.2.0
  go_router: ^6.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/
  - .env
  - assets/fonts/pretendard/  
  

